// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
WITH service_vars AS (
    SELECT price / NULLIF(duration, 0) AS price_per_minute
    FROM services
    WHERE id = $3
)
INSERT INTO bookings (
    user_id,
    zone_id,
    service_id,
    place_id,
    start_time,
    end_time,
    participants,
    total_price,
    status,
    contact_name,
    contact_email,
    contact_phone,
    details_json,
    created_at,
    updated_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::int,
    FLOOR(sv.price_per_minute * (EXTRACT(EPOCH FROM ($6::timestamptz - $5::timestamptz)) / 60) * $7::numeric),
    $8,
    $9,
    $10,
    $11,
    $12,
    NOW(),
    NOW()
FROM service_vars sv
RETURNING
    id,
    user_id,
    zone_id,
    service_id,
    place_id,
    start_time,
    end_time,
    participants,
    total_price,
    status,
    contact_name,
    contact_email,
    contact_phone,
    details_json,
    created_at,
    updated_at
`

type CreateBookingParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ZoneID       int64              `json:"zone_id"`
	ServiceID    int64              `json:"service_id"`
	PlaceID      pgtype.Int8        `json:"place_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Participants int32              `json:"participants"`
	Status       BookingStatus      `json:"status"`
	ContactName  string             `json:"contact_name"`
	ContactEmail string             `json:"contact_email"`
	ContactPhone string             `json:"contact_phone"`
	DetailsJson  []byte             `json:"details_json"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.ZoneID,
		arg.ServiceID,
		arg.PlaceID,
		arg.StartTime,
		arg.EndTime,
		arg.Participants,
		arg.Status,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.DetailsJson,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ServiceID,
		&i.PlaceID,
		&i.StartTime,
		&i.EndTime,
		&i.Participants,
		&i.TotalPrice,
		&i.Status,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :one
DELETE FROM bookings
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteBooking, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, user_id, zone_id, service_id, place_id, start_time, end_time, participants, total_price, status, contact_name, contact_email, contact_phone, details_json, created_at, updated_at
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ServiceID,
		&i.PlaceID,
		&i.StartTime,
		&i.EndTime,
		&i.Participants,
		&i.TotalPrice,
		&i.Status,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT id, user_id, zone_id, service_id, place_id, start_time, end_time, participants, total_price, status, contact_name, contact_email, contact_phone, details_json, created_at, updated_at
FROM bookings
ORDER BY id
`

func (q *Queries) ListBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ZoneID,
			&i.ServiceID,
			&i.PlaceID,
			&i.StartTime,
			&i.EndTime,
			&i.Participants,
			&i.TotalPrice,
			&i.Status,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, user_id, zone_id, service_id, place_id, start_time, end_time, participants, total_price, status, contact_name, contact_email, contact_phone, details_json, created_at, updated_at
FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByUser(ctx context.Context, userID pgtype.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ZoneID,
			&i.ServiceID,
			&i.PlaceID,
			&i.StartTime,
			&i.EndTime,
			&i.Participants,
			&i.TotalPrice,
			&i.Status,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByZoneID = `-- name: ListServicesByZoneID :many
SELECT id, name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at
FROM services
WHERE zone_id = $1 AND is_active = TRUE
ORDER BY id
`

func (q *Queries) ListServicesByZoneID(ctx context.Context, zoneID int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByZoneID, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZoneID,
			&i.Duration,
			&i.Price,
			&i.Currency,
			&i.Description,
			&i.IsActive,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchBooking = `-- name: PatchBooking :one
WITH current_booking AS (
    SELECT id, user_id, zone_id, service_id, place_id, start_time, end_time, participants, total_price, status, contact_name, contact_email, contact_phone, details_json, created_at, updated_at
    FROM bookings
    WHERE id = $1
),
new_values AS (
    SELECT
        COALESCE($2, cb.user_id) AS user_id,
        COALESCE($3, cb.zone_id) AS zone_id,
        COALESCE($4, cb.service_id) AS service_id,
        COALESCE($5, cb.start_time) AS start_time,
        COALESCE($6, cb.end_time) AS end_time,
        COALESCE($7, cb.participants) AS participants,
        COALESCE($8, cb.status) AS status
    FROM current_booking cb
),
service_vars AS (
    SELECT
        s.id,
        s.price / NULLIF(s.duration, 0) AS price_per_minute
    FROM services s
    JOIN new_values nv ON nv.service_id = s.id
)
UPDATE bookings b
SET
    user_id = nv.user_id,
    zone_id = nv.zone_id,
    service_id = nv.service_id,
    start_time = nv.start_time,
    end_time = nv.end_time,
    participants = nv.participants,
    total_price = FLOOR(
        sv.price_per_minute *
        (EXTRACT(EPOCH FROM (nv.end_time - nv.start_time)) / 60) *
        nv.participants
    ),
    status = nv.status,
    updated_at = NOW()
FROM new_values nv
JOIN service_vars sv ON sv.id = nv.service_id
WHERE b.id = $1
RETURNING
    b.id,
    b.user_id,
    b.zone_id,
    b.service_id,
    b.place_id,
    b.start_time,
    b.end_time,
    b.participants,
    b.total_price,
    b.status,
    b.contact_name,
    b.contact_email,
    b.contact_phone,
    b.details_json,
    b.created_at,
    b.updated_at
`

type PatchBookingParams struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	ServiceID    pgtype.Int8        `json:"service_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Participants pgtype.Int4        `json:"participants"`
	Status       NullBookingStatus  `json:"status"`
}

func (q *Queries) PatchBooking(ctx context.Context, arg PatchBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, patchBooking,
		arg.ID,
		arg.UserID,
		arg.ZoneID,
		arg.ServiceID,
		arg.StartTime,
		arg.EndTime,
		arg.Participants,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ServiceID,
		&i.PlaceID,
		&i.StartTime,
		&i.EndTime,
		&i.Participants,
		&i.TotalPrice,
		&i.Status,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
