// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
)

const createComputerConfiguration = `-- name: CreateComputerConfiguration :one
INSERT INTO computer_configurations (zone_tags_id, specs_json)
VALUES ($1, $2)
RETURNING id, zone_tags_id, specs_json
`

type CreateComputerConfigurationParams struct {
	ZoneTagsID int64  `json:"zone_tags_id"`
	SpecsJson  []byte `json:"specs_json"`
}

func (q *Queries) CreateComputerConfiguration(ctx context.Context, arg CreateComputerConfigurationParams) (ComputerConfiguration, error) {
	row := q.db.QueryRow(ctx, createComputerConfiguration, arg.ZoneTagsID, arg.SpecsJson)
	var i ComputerConfiguration
	err := row.Scan(&i.ID, &i.ZoneTagsID, &i.SpecsJson)
	return i, err
}

const createZoneTag = `-- name: CreateZoneTag :one
INSERT INTO zone_tags (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateZoneTag(ctx context.Context, name string) (ZoneTag, error) {
	row := q.db.QueryRow(ctx, createZoneTag, name)
	var i ZoneTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComputerConfigurationByID = `-- name: GetComputerConfigurationByID :one
SELECT id, zone_tags_id, specs_json
FROM computer_configurations
WHERE id = $1
`

func (q *Queries) GetComputerConfigurationByID(ctx context.Context, id int64) (ComputerConfiguration, error) {
	row := q.db.QueryRow(ctx, getComputerConfigurationByID, id)
	var i ComputerConfiguration
	err := row.Scan(&i.ID, &i.ZoneTagsID, &i.SpecsJson)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, settings_json, gallery_items_json, updated_at
FROM site_settings
WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SettingsJson,
		&i.GalleryItemsJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getZoneTagByID = `-- name: GetZoneTagByID :one
SELECT id, name, created_at, updated_at
FROM zone_tags
WHERE id = $1
`

func (q *Queries) GetZoneTagByID(ctx context.Context, id int32) (ZoneTag, error) {
	row := q.db.QueryRow(ctx, getZoneTagByID, id)
	var i ZoneTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComputerConfigurations = `-- name: ListComputerConfigurations :many
SELECT id, zone_tags_id, specs_json
FROM computer_configurations
ORDER BY id
`

func (q *Queries) ListComputerConfigurations(ctx context.Context) ([]ComputerConfiguration, error) {
	rows, err := q.db.Query(ctx, listComputerConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputerConfiguration
	for rows.Next() {
		var i ComputerConfiguration
		if err := rows.Scan(&i.ID, &i.ZoneTagsID, &i.SpecsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneTags = `-- name: ListZoneTags :many
SELECT id, name, created_at, updated_at
FROM zone_tags
ORDER BY id
`

func (q *Queries) ListZoneTags(ctx context.Context) ([]ZoneTag, error) {
	rows, err := q.db.Query(ctx, listZoneTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZoneTag
	for rows.Next() {
		var i ZoneTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteSettings = `-- name: UpsertSiteSettings :one
INSERT INTO site_settings (id, settings_json, gallery_items_json, updated_at)
VALUES (1, $1, $2, NOW())
ON CONFLICT (id) DO UPDATE
SET settings_json = EXCLUDED.settings_json,
    gallery_items_json = EXCLUDED.gallery_items_json,
    updated_at = NOW()
RETURNING id, settings_json, gallery_items_json, updated_at
`

type UpsertSiteSettingsParams struct {
	SettingsJson     []byte `json:"settings_json"`
	GalleryItemsJson []byte `json:"gallery_items_json"`
}

func (q *Queries) UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSettings, arg.SettingsJson, arg.GalleryItemsJson)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SettingsJson,
		&i.GalleryItemsJson,
		&i.UpdatedAt,
	)
	return i, err
}
