// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActionType string

const (
	ActionTypeCreate ActionType = "create"
	ActionTypeUpdate ActionType = "update"
	ActionTypeDelete ActionType = "delete"
	ActionTypeLogin  ActionType = "login"
	ActionTypeLogout ActionType = "logout"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType `json:"action_type"`
	Valid      bool       `json:"valid"` // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type BookingStatus string

const (
	BookingStatusCreated   BookingStatus = "created"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusCanceled  BookingStatus = "canceled"
	BookingStatusCompleted BookingStatus = "completed"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type EntityType string

const (
	EntityTypeBooking EntityType = "booking"
	EntityTypeService EntityType = "service"
	EntityTypeZone    EntityType = "zone"
	EntityTypePayment EntityType = "payment"
	EntityTypeUser    EntityType = "user"
	EntityTypeStaff   EntityType = "staff"
	EntityTypeOther   EntityType = "other"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType `json:"entity_type"`
	Valid      bool       `json:"valid"` // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

type PaymentMethod string

const (
	PaymentMethodCash   PaymentMethod = "cash"
	PaymentMethodCard   PaymentMethod = "card"
	PaymentMethodOnline PaymentMethod = "online"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending  PaymentStatus = "pending"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusFailed   PaymentStatus = "failed"
	PaymentStatusRefunded PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PositionType string

const (
	PositionTypeAdmin    PositionType = "admin"
	PositionTypeSeller   PositionType = "seller"
	PositionTypeOperator PositionType = "operator"
	PositionTypeTech     PositionType = "tech"
)

func (e *PositionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PositionType(s)
	case string:
		*e = PositionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PositionType: %T", src)
	}
	return nil
}

type NullPositionType struct {
	PositionType PositionType `json:"position_type"`
	Valid        bool         `json:"valid"` // Valid is true if PositionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPositionType) Scan(value interface{}) error {
	if value == nil {
		ns.PositionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PositionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPositionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PositionType), nil
}

type Role string

const (
	RoleAdmin  Role = "admin"
	RoleSeller Role = "seller"
	RoleClient Role = "client"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type ZoneType string

const (
	ZoneTypeGame   ZoneType = "game"
	ZoneTypeEvent  ZoneType = "event"
	ZoneTypeLounge ZoneType = "lounge"
	ZoneTypeSys    ZoneType = "sys"
)

func (e *ZoneType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ZoneType(s)
	case string:
		*e = ZoneType(s)
	default:
		return fmt.Errorf("unsupported scan type for ZoneType: %T", src)
	}
	return nil
}

type NullZoneType struct {
	ZoneType ZoneType `json:"zone_type"`
	Valid    bool     `json:"valid"` // Valid is true if ZoneType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullZoneType) Scan(value interface{}) error {
	if value == nil {
		ns.ZoneType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ZoneType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullZoneType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ZoneType), nil
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    ActionType         `json:"action"`
	Entity    EntityType         `json:"entity"`
	EntityID  pgtype.Int8        `json:"entity_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
}

type Booking struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ZoneID       int64              `json:"zone_id"`
	ServiceID    int64              `json:"service_id"`
	PlaceID      pgtype.Int8        `json:"place_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Participants int32              `json:"participants"`
	TotalPrice   pgtype.Numeric     `json:"total_price"`
	Status       BookingStatus      `json:"status"`
	ContactName  string             `json:"contact_name"`
	ContactEmail string             `json:"contact_email"`
	ContactPhone string             `json:"contact_phone"`
	DetailsJson  []byte             `json:"details_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ComputerConfiguration struct {
	ID         int64  `json:"id"`
	ZoneTagsID int64  `json:"zone_tags_id"`
	SpecsJson  []byte `json:"specs_json"`
}

type Payment struct {
	ID            int64              `json:"id"`
	BookingID     int64              `json:"booking_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	PaymentMethod PaymentMethod      `json:"payment_method"`
	Status        PaymentStatus      `json:"status"`
	ReceiptNumber pgtype.Text        `json:"receipt_number"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Ping struct {
	ID        int64              `json:"id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ZoneID      int64              `json:"zone_id"`
	Duration    int32              `json:"duration"`
	Price       pgtype.Numeric     `json:"price"`
	Currency    string             `json:"currency"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	DetailsJson []byte             `json:"details_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type SiteSetting struct {
	ID               int32              `json:"id"`
	SettingsJson     []byte             `json:"settings_json"`
	GalleryItemsJson []byte             `json:"gallery_items_json"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Staff struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Position  PositionType       `json:"position"`
	HireDate  pgtype.Date        `json:"hire_date"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	GoogleID  pgtype.Text        `json:"google_id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Phone     pgtype.Text        `json:"phone"`
	Role      Role               `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Zone struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ZoneType    ZoneType           `json:"zone_type"`
	ZoneTagID   int32              `json:"zone_tag_id"`
	Capacity    int32              `json:"capacity"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	DetailsJson []byte             `json:"details_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ZonePlace struct {
	ID              int64              `json:"id"`
	ZoneID          int64              `json:"zone_id"`
	Label           string             `json:"label"`
	ConfigurationID pgtype.Int8        `json:"configuration_id"`
	SortOrder       int32              `json:"sort_order"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ZoneTag struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
