// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, amount, currency, payment_method, status, receipt_number, paid_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, booking_id, amount, currency, payment_method, status, receipt_number, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID     int64              `json:"booking_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	PaymentMethod PaymentMethod      `json:"payment_method"`
	Status        PaymentStatus      `json:"status"`
	ReceiptNumber pgtype.Text        `json:"receipt_number"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.ReceiptNumber,
		arg.PaidAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ReceiptNumber,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :one
DELETE FROM payments
WHERE id = $1
RETURNING id
`

func (q *Queries) DeletePayment(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deletePayment, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, amount, currency, payment_method, status, receipt_number, paid_at, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ReceiptNumber,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, booking_id, amount, currency, payment_method, status, receipt_number, paid_at, created_at, updated_at
FROM payments
ORDER BY id
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.ReceiptNumber,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchPayment = `-- name: PatchPayment :one
UPDATE payments
SET booking_id = COALESCE($1, booking_id),
    amount = COALESCE($2, amount),
    currency = COALESCE($3, currency),
    payment_method = COALESCE($4, payment_method),
    status = COALESCE($5, status),
    receipt_number = COALESCE($6, receipt_number),
    paid_at = COALESCE($7, paid_at),
    updated_at = NOW()
WHERE id = $8
RETURNING id, booking_id, amount, currency, payment_method, status, receipt_number, paid_at, created_at, updated_at
`

type PatchPaymentParams struct {
	BookingID     pgtype.Int8        `json:"booking_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      pgtype.Text        `json:"currency"`
	PaymentMethod NullPaymentMethod  `json:"payment_method"`
	Status        NullPaymentStatus  `json:"status"`
	ReceiptNumber pgtype.Text        `json:"receipt_number"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	ID            int64              `json:"id"`
}

func (q *Queries) PatchPayment(ctx context.Context, arg PatchPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, patchPayment,
		arg.BookingID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.ReceiptNumber,
		arg.PaidAt,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.ReceiptNumber,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
