// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pings.sql

package sqlc

import (
	"context"
)

const createPing = `-- name: CreatePing :one
INSERT INTO pings (content)
VALUES ($1)
RETURNING id, content, created_at
`

func (q *Queries) CreatePing(ctx context.Context, content string) (Ping, error) {
	row := q.db.QueryRow(ctx, createPing, content)
	var i Ping
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt)
	return i, err
}

const listPings = `-- name: ListPings :many
SELECT id, content, created_at
FROM pings
ORDER BY created_at DESC
`

func (q *Queries) ListPings(ctx context.Context) ([]Ping, error) {
	rows, err := q.db.Query(ctx, listPings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ping
	for rows.Next() {
		var i Ping
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
