// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPlaceBookingOverlap = `-- name: CheckPlaceBookingOverlap :one
SELECT COUNT(*) AS conflict_count
FROM bookings
WHERE place_id = $1
  AND status NOT IN ('canceled')
  AND start_time < $2
  AND end_time > $3
`

type CheckPlaceBookingOverlapParams struct {
	PlaceID   pgtype.Int8        `json:"place_id"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) CheckPlaceBookingOverlap(ctx context.Context, arg CheckPlaceBookingOverlapParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkPlaceBookingOverlap, arg.PlaceID, arg.EndTime, arg.StartTime)
	var conflict_count int64
	err := row.Scan(&conflict_count)
	return conflict_count, err
}

const checkZoneBookingOverlap = `-- name: CheckZoneBookingOverlap :one
SELECT COUNT(*) AS conflict_count
FROM bookings
WHERE zone_id = $1
  AND service_id = $2
  AND status NOT IN ('canceled')
  AND start_time < $3
  AND end_time > $4
`

type CheckZoneBookingOverlapParams struct {
	ZoneID    int64              `json:"zone_id"`
	ServiceID int64              `json:"service_id"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) CheckZoneBookingOverlap(ctx context.Context, arg CheckZoneBookingOverlapParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkZoneBookingOverlap,
		arg.ZoneID,
		arg.ServiceID,
		arg.EndTime,
		arg.StartTime,
	)
	var conflict_count int64
	err := row.Scan(&conflict_count)
	return conflict_count, err
}

const countActiveBookingsForZone = `-- name: CountActiveBookingsForZone :one
SELECT COALESCE(SUM(participants), 0)::int AS booked_count
FROM bookings
WHERE zone_id = $1
  AND status NOT IN ('canceled')
  AND start_time < $2
  AND end_time > $3
`

type CountActiveBookingsForZoneParams struct {
	ZoneID    int64              `json:"zone_id"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) CountActiveBookingsForZone(ctx context.Context, arg CountActiveBookingsForZoneParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveBookingsForZone, arg.ZoneID, arg.EndTime, arg.StartTime)
	var booked_count int32
	err := row.Scan(&booked_count)
	return booked_count, err
}

const createZonePlace = `-- name: CreateZonePlace :one
INSERT INTO zone_places (zone_id, label, configuration_id, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, zone_id, label, configuration_id, sort_order, is_active, created_at, updated_at
`

type CreateZonePlaceParams struct {
	ZoneID          int64       `json:"zone_id"`
	Label           string      `json:"label"`
	ConfigurationID pgtype.Int8 `json:"configuration_id"`
	SortOrder       int32       `json:"sort_order"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateZonePlace(ctx context.Context, arg CreateZonePlaceParams) (ZonePlace, error) {
	row := q.db.QueryRow(ctx, createZonePlace,
		arg.ZoneID,
		arg.Label,
		arg.ConfigurationID,
		arg.SortOrder,
		arg.IsActive,
	)
	var i ZonePlace
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Label,
		&i.ConfigurationID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZonePlace = `-- name: DeleteZonePlace :execrows
DELETE FROM zone_places
WHERE id = $1
`

func (q *Queries) DeleteZonePlace(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteZonePlace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllZonePlaces = `-- name: GetAllZonePlaces :many
SELECT id, zone_id, label, configuration_id, sort_order, is_active, created_at, updated_at
FROM zone_places
ORDER BY sort_order, id
`

func (q *Queries) GetAllZonePlaces(ctx context.Context) ([]ZonePlace, error) {
	rows, err := q.db.Query(ctx, getAllZonePlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZonePlace
	for rows.Next() {
		var i ZonePlace
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Label,
			&i.ConfigurationID,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZonePlaceByID = `-- name: GetZonePlaceByID :one
SELECT id, zone_id, label, configuration_id, sort_order, is_active, created_at, updated_at
FROM zone_places
WHERE id = $1
`

func (q *Queries) GetZonePlaceByID(ctx context.Context, id int64) (ZonePlace, error) {
	row := q.db.QueryRow(ctx, getZonePlaceByID, id)
	var i ZonePlace
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Label,
		&i.ConfigurationID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveZonePlaces = `-- name: ListActiveZonePlaces :many
SELECT zp.id, zp.zone_id, zp.label, zp.configuration_id, zp.sort_order, zp.is_active, zp.created_at, zp.updated_at
FROM zone_places zp
WHERE zp.zone_id = $1 AND zp.is_active = TRUE
ORDER BY zp.sort_order, zp.id
`

func (q *Queries) ListActiveZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error) {
	rows, err := q.db.Query(ctx, listActiveZonePlaces, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZonePlace
	for rows.Next() {
		var i ZonePlace
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Label,
			&i.ConfigurationID,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonePlaces = `-- name: ListZonePlaces :many
SELECT id, zone_id, label, configuration_id, sort_order, is_active, created_at, updated_at
FROM zone_places
WHERE zone_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error) {
	rows, err := q.db.Query(ctx, listZonePlaces, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZonePlace
	for rows.Next() {
		var i ZonePlace
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Label,
			&i.ConfigurationID,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZonePlace = `-- name: UpdateZonePlace :one
UPDATE zone_places
SET
  label = COALESCE($1, label),
  configuration_id = COALESCE($2, configuration_id),
  sort_order = COALESCE($3, sort_order),
  is_active = COALESCE($4, is_active),
  updated_at = NOW()
WHERE id = $5
RETURNING id, zone_id, label, configuration_id, sort_order, is_active, created_at, updated_at
`

type UpdateZonePlaceParams struct {
	Label           pgtype.Text `json:"label"`
	ConfigurationID pgtype.Int8 `json:"configuration_id"`
	SortOrder       pgtype.Int4 `json:"sort_order"`
	IsActive        pgtype.Bool `json:"is_active"`
	ID              int64       `json:"id"`
}

func (q *Queries) UpdateZonePlace(ctx context.Context, arg UpdateZonePlaceParams) (ZonePlace, error) {
	row := q.db.QueryRow(ctx, updateZonePlace,
		arg.Label,
		arg.ConfigurationID,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	var i ZonePlace
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Label,
		&i.ConfigurationID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
