// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckPlaceBookingOverlap(ctx context.Context, arg CheckPlaceBookingOverlapParams) (int64, error)
	CheckZoneBookingOverlap(ctx context.Context, arg CheckZoneBookingOverlapParams) (int64, error)
	CountActiveBookingsForZone(ctx context.Context, arg CountActiveBookingsForZoneParams) (int32, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateComputerConfiguration(ctx context.Context, arg CreateComputerConfigurationParams) (ComputerConfiguration, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePing(ctx context.Context, content string) (Ping, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, userID pgtype.UUID) (Session, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	CreateZonePlace(ctx context.Context, arg CreateZonePlaceParams) (ZonePlace, error)
	CreateZoneTag(ctx context.Context, name string) (ZoneTag, error)
	DeleteBooking(ctx context.Context, id int64) (int64, error)
	DeleteComputerConfiguration(ctx context.Context, id int64) (int64, error)
	DeletePayment(ctx context.Context, id int64) (int64, error)
	DeleteService(ctx context.Context, id int64) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteShift(ctx context.Context, id int64) (int64, error)
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	DeleteZone(ctx context.Context, id int64) (int64, error)
	DeleteZonePlace(ctx context.Context, id int64) (int64, error)
	DeleteZoneTag(ctx context.Context, id int32) (int64, error)
	GetAllZonePlaces(ctx context.Context) ([]ZonePlace, error)
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	GetBookingByIDPublic(ctx context.Context, id int64) (Booking, error)
	GetComputerConfigurationByID(ctx context.Context, id int64) (ComputerConfiguration, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetServiceByID(ctx context.Context, id int64) (Service, error)
	GetServiceDurationsByZoneTag(ctx context.Context, zoneTagID int32) ([]int32, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error)
	GetShiftByID(ctx context.Context, id int64) (GetShiftByIDRow, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetZoneByID(ctx context.Context, id int64) (Zone, error)
	GetZonePlaceByID(ctx context.Context, id int64) (ZonePlace, error)
	GetZoneTagByID(ctx context.Context, id int32) (ZoneTag, error)
	// Returns true if any existing shift for the same zone_tag_id overlaps with the given window.
	// exclude_id is used on PATCH to exclude the shift being updated (pass 0 to skip).
	HasOverlappingShift(ctx context.Context, arg HasOverlappingShiftParams) (bool, error)
	ListActiveZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error)
	ListBookings(ctx context.Context) ([]Booking, error)
	ListBookingsByUser(ctx context.Context, userID pgtype.UUID) ([]Booking, error)
	ListComputerConfigurations(ctx context.Context) ([]ComputerConfiguration, error)
	ListComputerConfigurationsByZoneTagIDs(ctx context.Context, dollar_1 []int64) ([]ComputerConfiguration, error)
	ListLoungeBookingsForDate(ctx context.Context, arg ListLoungeBookingsForDateParams) ([]ListLoungeBookingsForDateRow, error)
	ListPayments(ctx context.Context) ([]Payment, error)
	ListPings(ctx context.Context) ([]Ping, error)
	ListSellers(ctx context.Context) ([]User, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListServicesByZoneID(ctx context.Context, zoneID int64) ([]Service, error)
	ListShifts(ctx context.Context) ([]ListShiftsRow, error)
	ListShiftsByZoneTagID(ctx context.Context, zoneTagID pgtype.Int8) ([]ListShiftsByZoneTagIDRow, error)
	ListUserZoneTags(ctx context.Context) ([]ZoneTag, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListZonePlaceBookingsForDate(ctx context.Context, arg ListZonePlaceBookingsForDateParams) ([]ListZonePlaceBookingsForDateRow, error)
	ListZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error)
	ListZoneTags(ctx context.Context) ([]ZoneTag, error)
	ListZones(ctx context.Context) ([]Zone, error)
	ListZonesByType(ctx context.Context, zoneType ZoneType) ([]Zone, error)
	ListZonesWithServices(ctx context.Context) ([]Zone, error)
	PatchBooking(ctx context.Context, arg PatchBookingParams) (Booking, error)
	PatchComputerConfiguration(ctx context.Context, arg PatchComputerConfigurationParams) (ComputerConfiguration, error)
	PatchPayment(ctx context.Context, arg PatchPaymentParams) (Payment, error)
	PatchService(ctx context.Context, arg PatchServiceParams) (Service, error)
	PatchShift(ctx context.Context, arg PatchShiftParams) (Shift, error)
	PatchUser(ctx context.Context, arg PatchUserParams) (User, error)
	PatchZone(ctx context.Context, arg PatchZoneParams) (Zone, error)
	PatchZoneTag(ctx context.Context, arg PatchZoneTagParams) (ZoneTag, error)
	SearchUsersByEmail(ctx context.Context, query pgtype.Text) ([]User, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error)
	UpdateZonePlace(ctx context.Context, arg UpdateZonePlaceParams) (ZonePlace, error)
	UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) (SiteSetting, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
