// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckPlaceBookingOverlap(ctx context.Context, arg CheckPlaceBookingOverlapParams) (int64, error)
	CheckZoneBookingOverlap(ctx context.Context, arg CheckZoneBookingOverlapParams) (int64, error)
	CountActiveBookingsForZone(ctx context.Context, arg CountActiveBookingsForZoneParams) (int32, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateComputerConfiguration(ctx context.Context, arg CreateComputerConfigurationParams) (ComputerConfiguration, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePing(ctx context.Context, content string) (Ping, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, userID pgtype.UUID) (Session, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	CreateZonePlace(ctx context.Context, arg CreateZonePlaceParams) (ZonePlace, error)
	CreateZoneTag(ctx context.Context, name string) (ZoneTag, error)
	DeleteBooking(ctx context.Context, id int64) (int64, error)
	DeletePayment(ctx context.Context, id int64) (int64, error)
	DeleteService(ctx context.Context, id int64) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteStaff(ctx context.Context, id int64) (int64, error)
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	DeleteZone(ctx context.Context, id int64) (int64, error)
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	GetComputerConfigurationByID(ctx context.Context, id int64) (ComputerConfiguration, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetServiceByID(ctx context.Context, id int64) (Service, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetStaffByID(ctx context.Context, id int64) (Staff, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetZoneByID(ctx context.Context, id int64) (Zone, error)
	GetZonePlaceByID(ctx context.Context, id int64) (ZonePlace, error)
	GetZoneTagByID(ctx context.Context, id int32) (ZoneTag, error)
	ListActiveZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error)
	ListBookings(ctx context.Context) ([]Booking, error)
	ListBookingsByUser(ctx context.Context, userID pgtype.UUID) ([]Booking, error)
	ListComputerConfigurations(ctx context.Context) ([]ComputerConfiguration, error)
	ListPayments(ctx context.Context) ([]Payment, error)
	ListPings(ctx context.Context) ([]Ping, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListServicesByZoneID(ctx context.Context, zoneID int64) ([]Service, error)
	ListStaff(ctx context.Context) ([]Staff, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListZonePlaces(ctx context.Context, zoneID int64) ([]ZonePlace, error)
	ListZoneTags(ctx context.Context) ([]ZoneTag, error)
	ListZones(ctx context.Context) ([]Zone, error)
	ListZonesByType(ctx context.Context, zoneType ZoneType) ([]Zone, error)
	ListZonesWithServices(ctx context.Context) ([]Zone, error)
	PatchBooking(ctx context.Context, arg PatchBookingParams) (Booking, error)
	PatchPayment(ctx context.Context, arg PatchPaymentParams) (Payment, error)
	PatchService(ctx context.Context, arg PatchServiceParams) (Service, error)
	PatchStaff(ctx context.Context, arg PatchStaffParams) (Staff, error)
	PatchZone(ctx context.Context, arg PatchZoneParams) (Zone, error)
	UpsertSiteSettings(ctx context.Context, arg UpsertSiteSettingsParams) (SiteSetting, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
