// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at
`

type CreateServiceParams struct {
	Name        string         `json:"name"`
	ZoneID      int64          `json:"zone_id"`
	Duration    int32          `json:"duration"`
	Price       pgtype.Numeric `json:"price"`
	Currency    string         `json:"currency"`
	Description pgtype.Text    `json:"description"`
	IsActive    bool           `json:"is_active"`
	DetailsJson []byte         `json:"details_json"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.ZoneID,
		arg.Duration,
		arg.Price,
		arg.Currency,
		arg.Description,
		arg.IsActive,
		arg.DetailsJson,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneID,
		&i.Duration,
		&i.Price,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :one
DELETE FROM services WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteService(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteService, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneID,
		&i.Duration,
		&i.Price,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at FROM services
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZoneID,
			&i.Duration,
			&i.Price,
			&i.Currency,
			&i.Description,
			&i.IsActive,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchService = `-- name: PatchService :one
UPDATE services
SET name = COALESCE($1, name),
    zone_id = COALESCE($2, zone_id),
    duration = COALESCE($3, duration),
    price = COALESCE($4, price),
    currency = COALESCE($5, currency),
    description = COALESCE($6, description),
    is_active = COALESCE($7, is_active),
    details_json = COALESCE($8, details_json),
    updated_at = NOW()
WHERE id = $9
RETURNING id, name, zone_id, duration, price, currency, description, is_active, details_json, created_at, updated_at
`

type PatchServiceParams struct {
	Name        pgtype.Text    `json:"name"`
	ZoneID      pgtype.Int8    `json:"zone_id"`
	Duration    pgtype.Int4    `json:"duration"`
	Price       pgtype.Numeric `json:"price"`
	Currency    pgtype.Text    `json:"currency"`
	Description pgtype.Text    `json:"description"`
	IsActive    pgtype.Bool    `json:"is_active"`
	DetailsJson []byte         `json:"details_json"`
	ID          int64          `json:"id"`
}

func (q *Queries) PatchService(ctx context.Context, arg PatchServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, patchService,
		arg.Name,
		arg.ZoneID,
		arg.Duration,
		arg.Price,
		arg.Currency,
		arg.Description,
		arg.IsActive,
		arg.DetailsJson,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneID,
		&i.Duration,
		&i.Price,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
