// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shifts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (user_id, zone_tag_id, start_time, end_time, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, zone_tag_id, start_time, end_time, note, created_at, updated_at, deleted_at
`

type CreateShiftParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ZoneTagID pgtype.Int8        `json:"zone_tag_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Note      pgtype.Text        `json:"note"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift,
		arg.UserID,
		arg.ZoneTagID,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneTagID,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteShift = `-- name: DeleteShift :one
UPDATE shifts
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteShift(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteShift, id)
	err := row.Scan(&id)
	return id, err
}

const getShiftByID = `-- name: GetShiftByID :one
SELECT shifts.id, shifts.user_id, shifts.zone_tag_id, shifts.start_time, shifts.end_time, shifts.note, shifts.created_at, shifts.updated_at, shifts.deleted_at, users.id, users.google_id, users.full_name, users.email, users.avatar_url, users.phone, users.role, users.is_active, users.created_at, users.updated_at, users.deleted_at
FROM shifts
JOIN users ON users.id = shifts.user_id
WHERE shifts.id = $1 AND shifts.deleted_at IS NULL
`

type GetShiftByIDRow struct {
	Shift Shift `json:"shift"`
	User  User  `json:"user"`
}

func (q *Queries) GetShiftByID(ctx context.Context, id int64) (GetShiftByIDRow, error) {
	row := q.db.QueryRow(ctx, getShiftByID, id)
	var i GetShiftByIDRow
	err := row.Scan(
		&i.Shift.ID,
		&i.Shift.UserID,
		&i.Shift.ZoneTagID,
		&i.Shift.StartTime,
		&i.Shift.EndTime,
		&i.Shift.Note,
		&i.Shift.CreatedAt,
		&i.Shift.UpdatedAt,
		&i.Shift.DeletedAt,
		&i.User.ID,
		&i.User.GoogleID,
		&i.User.FullName,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Phone,
		&i.User.Role,
		&i.User.IsActive,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
	)
	return i, err
}

const hasOverlappingShift = `-- name: HasOverlappingShift :one
SELECT EXISTS (
  SELECT 1
  FROM shifts
  WHERE zone_tag_id = $1
    AND deleted_at IS NULL
    AND id <> $2
    AND start_time < $3
    AND end_time   > $4
) AS overlaps
`

type HasOverlappingShiftParams struct {
	ZoneTagID pgtype.Int8        `json:"zone_tag_id"`
	ExcludeID int64              `json:"exclude_id"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

// Returns true if any existing shift for the same zone_tag_id overlaps with the given window.
// exclude_id is used on PATCH to exclude the shift being updated (pass 0 to skip).
func (q *Queries) HasOverlappingShift(ctx context.Context, arg HasOverlappingShiftParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOverlappingShift,
		arg.ZoneTagID,
		arg.ExcludeID,
		arg.EndTime,
		arg.StartTime,
	)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const listShifts = `-- name: ListShifts :many
SELECT shifts.id, shifts.user_id, shifts.zone_tag_id, shifts.start_time, shifts.end_time, shifts.note, shifts.created_at, shifts.updated_at, shifts.deleted_at, users.id, users.google_id, users.full_name, users.email, users.avatar_url, users.phone, users.role, users.is_active, users.created_at, users.updated_at, users.deleted_at
FROM shifts
JOIN users ON users.id = shifts.user_id
WHERE shifts.deleted_at IS NULL
ORDER BY shifts.start_time DESC, shifts.id DESC
`

type ListShiftsRow struct {
	Shift Shift `json:"shift"`
	User  User  `json:"user"`
}

func (q *Queries) ListShifts(ctx context.Context) ([]ListShiftsRow, error) {
	rows, err := q.db.Query(ctx, listShifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftsRow
	for rows.Next() {
		var i ListShiftsRow
		if err := rows.Scan(
			&i.Shift.ID,
			&i.Shift.UserID,
			&i.Shift.ZoneTagID,
			&i.Shift.StartTime,
			&i.Shift.EndTime,
			&i.Shift.Note,
			&i.Shift.CreatedAt,
			&i.Shift.UpdatedAt,
			&i.Shift.DeletedAt,
			&i.User.ID,
			&i.User.GoogleID,
			&i.User.FullName,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Phone,
			&i.User.Role,
			&i.User.IsActive,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftsByZoneTagID = `-- name: ListShiftsByZoneTagID :many
SELECT shifts.id, shifts.user_id, shifts.zone_tag_id, shifts.start_time, shifts.end_time, shifts.note, shifts.created_at, shifts.updated_at, shifts.deleted_at, users.id, users.google_id, users.full_name, users.email, users.avatar_url, users.phone, users.role, users.is_active, users.created_at, users.updated_at, users.deleted_at
FROM shifts
JOIN users ON users.id = shifts.user_id
WHERE shifts.zone_tag_id = $1
  AND shifts.deleted_at IS NULL
ORDER BY shifts.start_time ASC
`

type ListShiftsByZoneTagIDRow struct {
	Shift Shift `json:"shift"`
	User  User  `json:"user"`
}

func (q *Queries) ListShiftsByZoneTagID(ctx context.Context, zoneTagID pgtype.Int8) ([]ListShiftsByZoneTagIDRow, error) {
	rows, err := q.db.Query(ctx, listShiftsByZoneTagID, zoneTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftsByZoneTagIDRow
	for rows.Next() {
		var i ListShiftsByZoneTagIDRow
		if err := rows.Scan(
			&i.Shift.ID,
			&i.Shift.UserID,
			&i.Shift.ZoneTagID,
			&i.Shift.StartTime,
			&i.Shift.EndTime,
			&i.Shift.Note,
			&i.Shift.CreatedAt,
			&i.Shift.UpdatedAt,
			&i.Shift.DeletedAt,
			&i.User.ID,
			&i.User.GoogleID,
			&i.User.FullName,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Phone,
			&i.User.Role,
			&i.User.IsActive,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchShift = `-- name: PatchShift :one
UPDATE shifts
SET zone_tag_id = COALESCE($1, zone_tag_id),
    start_time = COALESCE($2, start_time),
    end_time = COALESCE($3, end_time),
    note = COALESCE($4, note),
    updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, user_id, zone_tag_id, start_time, end_time, note, created_at, updated_at, deleted_at
`

type PatchShiftParams struct {
	ZoneTagID pgtype.Int8        `json:"zone_tag_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Note      pgtype.Text        `json:"note"`
	ID        int64              `json:"id"`
}

func (q *Queries) PatchShift(ctx context.Context, arg PatchShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, patchShift,
		arg.ZoneTagID,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
		arg.ID,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneTagID,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
