// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (user_id, position, hire_date, phone, email, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, position, hire_date, phone, email, is_active, created_at, updated_at, deleted_at
`

type CreateStaffParams struct {
	UserID   pgtype.UUID  `json:"user_id"`
	Position PositionType `json:"position"`
	HireDate pgtype.Date  `json:"hire_date"`
	Phone    pgtype.Text  `json:"phone"`
	Email    pgtype.Text  `json:"email"`
	IsActive bool         `json:"is_active"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.UserID,
		arg.Position,
		arg.HireDate,
		arg.Phone,
		arg.Email,
		arg.IsActive,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.HireDate,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :one
UPDATE staff
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteStaff(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteStaff, id)
	err := row.Scan(&id)
	return id, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, user_id, position, hire_date, phone, email, is_active, created_at, updated_at, deleted_at
FROM staff
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStaffByID(ctx context.Context, id int64) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.HireDate,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, user_id, position, hire_date, phone, email, is_active, created_at, updated_at, deleted_at
FROM staff
WHERE deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListStaff(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Position,
			&i.HireDate,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchStaff = `-- name: PatchStaff :one
UPDATE staff
SET position = COALESCE($1, position),
    hire_date = COALESCE($2, hire_date),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, user_id, position, hire_date, phone, email, is_active, created_at, updated_at, deleted_at
`

type PatchStaffParams struct {
	Position NullPositionType `json:"position"`
	HireDate pgtype.Date      `json:"hire_date"`
	Phone    pgtype.Text      `json:"phone"`
	Email    pgtype.Text      `json:"email"`
	IsActive pgtype.Bool      `json:"is_active"`
	ID       int64            `json:"id"`
}

func (q *Queries) PatchStaff(ctx context.Context, arg PatchStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, patchStaff,
		arg.Position,
		arg.HireDate,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.ID,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.HireDate,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
