// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingsByZoneType = `-- name: GetBookingsByZoneType :many
SELECT
    z.zone_type,
    COUNT(*) AS count
FROM bookings b
JOIN zones z ON b.zone_id = z.id
GROUP BY z.zone_type
`

type GetBookingsByZoneTypeRow struct {
	ZoneType ZoneType `json:"zone_type"`
	Count    int64    `json:"count"`
}

func (q *Queries) GetBookingsByZoneType(ctx context.Context) ([]GetBookingsByZoneTypeRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByZoneType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByZoneTypeRow
	for rows.Next() {
		var i GetBookingsByZoneTypeRow
		if err := rows.Scan(&i.ZoneType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsLast30Days = `-- name: GetBookingsLast30Days :many
SELECT
    DATE_TRUNC('day', created_at)::DATE AS date,
    COUNT(*) AS count
FROM bookings
WHERE created_at > NOW() - INTERVAL '30 days'
GROUP BY 1
ORDER BY 1
`

type GetBookingsLast30DaysRow struct {
	Date  pgtype.Date `json:"date"`
	Count int64       `json:"count"`
}

func (q *Queries) GetBookingsLast30Days(ctx context.Context) ([]GetBookingsLast30DaysRow, error) {
	rows, err := q.db.Query(ctx, getBookingsLast30Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsLast30DaysRow
	for rows.Next() {
		var i GetBookingsLast30DaysRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueLast30Days = `-- name: GetRevenueLast30Days :many
SELECT
    DATE_TRUNC('day', paid_at)::DATE AS date,
    SUM(amount)::NUMERIC AS revenue
FROM payments
WHERE status = 'paid' AND paid_at > NOW() - INTERVAL '30 days'
GROUP BY 1
ORDER BY 1
`

type GetRevenueLast30DaysRow struct {
	Date    pgtype.Date    `json:"date"`
	Revenue pgtype.Numeric `json:"revenue"`
}

func (q *Queries) GetRevenueLast30Days(ctx context.Context) ([]GetRevenueLast30DaysRow, error) {
	rows, err := q.db.Query(ctx, getRevenueLast30Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueLast30DaysRow
	for rows.Next() {
		var i GetRevenueLast30DaysRow
		if err := rows.Scan(&i.Date, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryStats = `-- name: GetSummaryStats :one
SELECT
    (SELECT COUNT(*) FROM bookings) AS total_bookings,
    (SELECT COALESCE(SUM(amount), 0)::NUMERIC FROM payments WHERE status = 'paid') AS total_revenue,
    (SELECT COUNT(*) FROM users WHERE is_active = TRUE) AS active_users,
    (SELECT COUNT(*) FROM bookings WHERE status = 'created') AS pending_bookings
`

type GetSummaryStatsRow struct {
	TotalBookings   int64          `json:"total_bookings"`
	TotalRevenue    pgtype.Numeric `json:"total_revenue"`
	ActiveUsers     int64          `json:"active_users"`
	PendingBookings int64          `json:"pending_bookings"`
}

func (q *Queries) GetSummaryStats(ctx context.Context) (GetSummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, getSummaryStats)
	var i GetSummaryStatsRow
	err := row.Scan(
		&i.TotalBookings,
		&i.TotalRevenue,
		&i.ActiveUsers,
		&i.PendingBookings,
	)
	return i, err
}
