// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_id, full_name, email, avatar_url, role)
VALUES ($1, $2, $3, $4, 'client')
ON CONFLICT (email) DO UPDATE
SET google_id = EXCLUDED.google_id,
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, google_id, full_name, email, avatar_url, phone, role, is_active, created_at, updated_at, deleted_at
`

type UpsertUserParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	FullName  string      `json:"full_name"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleID,
		arg.FullName,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
