// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUsers = `-- name: ListUsers :many
SELECT id, google_id, full_name, email, avatar_url, phone, role, is_active, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.FullName,
			&i.Email,
			&i.AvatarUrl,
			&i.Phone,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchUser = `-- name: PatchUser :one
UPDATE users
SET full_name = COALESCE($1, full_name),
    phone = COALESCE($2, phone),
    updated_at = NOW()
WHERE id = $3
RETURNING id, google_id, full_name, email, avatar_url, phone, role, is_active, created_at, updated_at, deleted_at
`

type PatchUserParams struct {
	FullName pgtype.Text `json:"full_name"`
	Phone    pgtype.Text `json:"phone"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) PatchUser(ctx context.Context, arg PatchUserParams) (User, error) {
	row := q.db.QueryRow(ctx, patchUser, arg.FullName, arg.Phone, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_id, full_name, email, avatar_url, role)
VALUES ($1, $2, $3, $4, 'client')
ON CONFLICT (email) DO UPDATE
SET google_id = EXCLUDED.google_id,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, google_id, full_name, email, avatar_url, phone, role, is_active, created_at, updated_at, deleted_at
`

type UpsertUserParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	FullName  string      `json:"full_name"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleID,
		arg.FullName,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
