// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createZone = `-- name: CreateZone :one
INSERT INTO zones (name, zone_type, zone_tag_id, capacity, description, is_active, details_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, zone_type, zone_tag_id, capacity, description, is_active, details_json, created_at, updated_at
`

type CreateZoneParams struct {
	Name        string      `json:"name"`
	ZoneType    ZoneType    `json:"zone_type"`
	ZoneTagID   pgtype.Int4 `json:"zone_tag_id"`
	Capacity    int32       `json:"capacity"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	DetailsJson []byte      `json:"details_json"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.Name,
		arg.ZoneType,
		arg.ZoneTagID,
		arg.Capacity,
		arg.Description,
		arg.IsActive,
		arg.DetailsJson,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneType,
		&i.ZoneTagID,
		&i.Capacity,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :one
DELETE FROM zones
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteZone(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteZone, id)
	err := row.Scan(&id)
	return id, err
}

const getZoneByID = `-- name: GetZoneByID :one
SELECT id, name, zone_type, zone_tag_id, capacity, description, is_active, details_json, created_at, updated_at
FROM zones
WHERE id = $1
`

func (q *Queries) GetZoneByID(ctx context.Context, id int64) (Zone, error) {
	row := q.db.QueryRow(ctx, getZoneByID, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneType,
		&i.ZoneTagID,
		&i.Capacity,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT id, name, zone_type, zone_tag_id, capacity, description, is_active, details_json, created_at, updated_at
FROM zones
ORDER BY id
`

func (q *Queries) ListZones(ctx context.Context) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZoneType,
			&i.ZoneTagID,
			&i.Capacity,
			&i.Description,
			&i.IsActive,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByType = `-- name: ListZonesByType :many
SELECT id, name, zone_type, zone_tag_id, capacity, description, is_active, details_json, created_at, updated_at
FROM zones
WHERE zone_type = $1 AND is_active = TRUE
ORDER BY id
`

func (q *Queries) ListZonesByType(ctx context.Context, zoneType ZoneType) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZonesByType, zoneType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZoneType,
			&i.ZoneTagID,
			&i.Capacity,
			&i.Description,
			&i.IsActive,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesWithServices = `-- name: ListZonesWithServices :many
SELECT z.id, z.name, z.zone_type, z.zone_tag_id, z.capacity, z.description, z.is_active, z.details_json, z.created_at, z.updated_at
FROM zones z
WHERE z.is_active = TRUE
ORDER BY z.id
`

func (q *Queries) ListZonesWithServices(ctx context.Context) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZonesWithServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZoneType,
			&i.ZoneTagID,
			&i.Capacity,
			&i.Description,
			&i.IsActive,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchZone = `-- name: PatchZone :one
UPDATE zones
SET name = COALESCE($1, name),
    zone_type = COALESCE($2, zone_type),
    zone_tag_id = COALESCE($3, zone_tag_id),
    capacity = COALESCE($4, capacity),
    description = COALESCE($5, description),
    is_active = COALESCE($6, is_active),
    details_json = COALESCE($7, details_json),
    updated_at = NOW()
WHERE id = $8
RETURNING id, name, zone_type, zone_tag_id, capacity, description, is_active, details_json, created_at, updated_at
`

type PatchZoneParams struct {
	Name        pgtype.Text  `json:"name"`
	ZoneType    NullZoneType `json:"zone_type"`
	ZoneTagID   pgtype.Int4  `json:"zone_tag_id"`
	Capacity    pgtype.Int4  `json:"capacity"`
	Description pgtype.Text  `json:"description"`
	IsActive    pgtype.Bool  `json:"is_active"`
	DetailsJson []byte       `json:"details_json"`
	ID          int64        `json:"id"`
}

func (q *Queries) PatchZone(ctx context.Context, arg PatchZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, patchZone,
		arg.Name,
		arg.ZoneType,
		arg.ZoneTagID,
		arg.Capacity,
		arg.Description,
		arg.IsActive,
		arg.DetailsJson,
		arg.ID,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZoneType,
		&i.ZoneTagID,
		&i.Capacity,
		&i.Description,
		&i.IsActive,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
