// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/{provider}": {
            "get": {
                "description": "Redirects to provider authorization page",
                "tags": [
                    "auth"
                ],
                "summary": "Start OAuth",
                "parameters": [
                    {
                        "enum": [
                            "google"
                        ],
                        "type": "string",
                        "description": "OAuth provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to provider",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/{provider}/callback": {
            "get": {
                "description": "Completes OAuth flow and returns user profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "OAuth callback",
                "parameters": [
                    {
                        "enum": [
                            "google"
                        ],
                        "type": "string",
                        "description": "OAuth provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/booking": {
            "get": {
                "description": "Returns all bookings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "List bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BookingListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a booking from JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Create booking",
                "parameters": [
                    {
                        "description": "Booking payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/booking/{id}": {
            "get": {
                "description": "Returns booking by id from path param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get booking by id",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes booking by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Delete booking",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeleteBookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates booking fields by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Patch booking",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Booking patch payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/payment": {
            "get": {
                "description": "Returns all payments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "List payments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PaymentListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a payment from JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Create payment",
                "parameters": [
                    {
                        "description": "Payment payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/payment/{id}": {
            "get": {
                "description": "Returns payment by id from path param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Get payment by id",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes payment by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Delete payment",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeletePaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates payment fields by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Patch payment",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment patch payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "Returns pong with timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pong": {
            "get": {
                "description": "Returns ping with timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Pong",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service": {
            "get": {
                "description": "Returns all services",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "List services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ServiceListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a service from JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Create service",
                "parameters": [
                    {
                        "description": "Service payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service/{id}": {
            "get": {
                "description": "Returns service id from path param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get service by id",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes service by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Delete service",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeleteServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates service fields by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Patch service",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service patch payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff": {
            "get": {
                "description": "Returns all staff members",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "List staff",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StaffListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a staff member from JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Create staff",
                "parameters": [
                    {
                        "description": "Staff payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.StaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff/{id}": {
            "get": {
                "description": "Returns staff member by id from path param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get staff by id",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes staff member by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Delete staff",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeleteStaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates staff fields by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Patch staff",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Staff patch payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "description": "Returns all active users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/zone": {
            "get": {
                "description": "Returns all zones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "List zones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ZoneListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a zone from JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Create zone",
                "parameters": [
                    {
                        "description": "Zone payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateZoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/zone/{id}": {
            "get": {
                "description": "Returns zone id from path param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Get zone by id",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Zone ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes zone by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Delete zone",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Zone ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeleteZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates zone fields by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Patch zone",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Zone ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Zone patch payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchZoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns service status and timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Pings database and returns readiness status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateBookingRequest": {
            "type": "object",
            "required": [
                "end_time",
                "participants",
                "service_id",
                "start_time",
                "status",
                "user_id",
                "zone_id"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "participants": {
                    "type": "integer",
                    "minimum": 1
                },
                "service_id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "created",
                        "confirmed",
                        "canceled",
                        "completed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.BookingStatus"
                        }
                    ]
                },
                "user_id": {
                    "type": "string"
                },
                "zone_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "booking_id",
                "currency",
                "payment_method"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                },
                "booking_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_method": {
                    "enum": [
                        "cash",
                        "card",
                        "online"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PaymentMethod"
                        }
                    ]
                },
                "receipt_number": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "pending",
                        "paid",
                        "failed",
                        "refunded"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PaymentStatus"
                        }
                    ]
                }
            }
        },
        "domain.CreateServiceRequest": {
            "type": "object",
            "required": [
                "currency",
                "description",
                "duration",
                "name",
                "price",
                "zone_id"
            ],
            "properties": {
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "zone_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateStaffRequest": {
            "type": "object",
            "required": [
                "hire_date",
                "position",
                "user_id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "hire_date": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "position": {
                    "enum": [
                        "admin",
                        "seller",
                        "operator",
                        "tech"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PositionType"
                        }
                    ]
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateZoneRequest": {
            "type": "object",
            "required": [
                "capacity",
                "name",
                "type"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "game",
                        "event",
                        "vip",
                        "lounge",
                        "sys"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.ZoneType"
                        }
                    ]
                }
            }
        },
        "domain.PatchBookingRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "participants": {
                    "type": "integer",
                    "minimum": 1
                },
                "service_id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "created",
                        "confirmed",
                        "canceled",
                        "completed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.BookingStatus"
                        }
                    ]
                },
                "user_id": {
                    "type": "string"
                },
                "zone_id": {
                    "type": "integer"
                }
            }
        },
        "domain.PatchPaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "booking_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_method": {
                    "enum": [
                        "cash",
                        "card",
                        "online"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PaymentMethod"
                        }
                    ]
                },
                "receipt_number": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "pending",
                        "paid",
                        "failed",
                        "refunded"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PaymentStatus"
                        }
                    ]
                }
            }
        },
        "domain.PatchStaffRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "hire_date": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "position": {
                    "enum": [
                        "admin",
                        "seller",
                        "operator",
                        "tech"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.PositionType"
                        }
                    ]
                }
            }
        },
        "domain.PatchZoneRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "game",
                        "event",
                        "vip",
                        "lounge",
                        "sys"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sqlc.ZoneType"
                        }
                    ]
                }
            }
        },
        "domain.UpdateServiceRequest": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "zone_id": {
                    "type": "integer"
                }
            }
        },
        "response.AuthResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "user": {
                    "$ref": "#/definitions/response.AuthUserResponse"
                }
            }
        },
        "response.AuthUserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ada Lovelace"
                },
                "provider": {
                    "type": "string",
                    "example": "google"
                }
            }
        },
        "response.BookingDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-03-20T11:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "participants": {
                    "type": "integer",
                    "example": 4
                },
                "service_id": {
                    "type": "integer",
                    "example": 1
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-03-20T10:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "created"
                },
                "total_price": {
                    "type": "string",
                    "example": "1500.00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "zone_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "response.BookingListResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.BookingDoc"
                    }
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.BookingResponse": {
            "type": "object",
            "properties": {
                "booking": {
                    "$ref": "#/definitions/response.BookingDoc"
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.DeleteBookingResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.DeletePaymentResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.DeleteServiceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.DeleteStaffResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.DeleteZoneResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "auth_failed"
                },
                "details": {},
                "message": {
                    "type": "string",
                    "example": "Authentication failed"
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.HealthResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.PaymentDoc": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "1500.00"
                },
                "booking_id": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "currency": {
                    "type": "string",
                    "example": "RUB"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "paid_at": {
                    "type": "string",
                    "example": "2026-03-22T15:00:00Z"
                },
                "payment_method": {
                    "type": "string",
                    "example": "card"
                },
                "receipt_number": {
                    "type": "string",
                    "example": "RCP-001"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.PaymentListResponse": {
            "type": "object",
            "properties": {
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PaymentDoc"
                    }
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.PaymentResponse": {
            "type": "object",
            "properties": {
                "payment": {
                    "$ref": "#/definitions/response.PaymentDoc"
                },
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.ServiceDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "description": {
                    "type": "string",
                    "example": "1 hour of VIP PS5"
                },
                "duration": {
                    "type": "integer",
                    "example": 60
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "VIP Gaming"
                },
                "price": {
                    "type": "string",
                    "example": "15.00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "zone_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "response.ServiceListResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ServiceDoc"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.ServiceResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "service": {
                    "$ref": "#/definitions/response.ServiceDoc"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.StaffDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "email": {
                    "type": "string",
                    "example": "staff@example.com"
                },
                "hire_date": {
                    "type": "string",
                    "example": "2026-01-15"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "phone": {
                    "type": "string",
                    "example": "+79001234567"
                },
                "position": {
                    "type": "string",
                    "example": "admin"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "response.StaffListResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "staff": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.StaffDoc"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.StaffResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "staff": {
                    "$ref": "#/definitions/response.StaffDoc"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                }
            }
        },
        "response.ZoneDoc": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 20
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "description": {
                    "type": "string",
                    "example": "Large hall"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Main Hall"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "zone_type": {
                    "type": "string",
                    "example": "game"
                }
            }
        },
        "response.ZoneListResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "zones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ZoneDoc"
                    }
                }
            }
        },
        "response.ZoneResponse": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "7fbd6854-8e42-4451-80ee-6da60aeceacd"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-19T15:37:27.514667373Z"
                },
                "zone": {
                    "$ref": "#/definitions/response.ZoneDoc"
                }
            }
        },
        "sqlc.BookingStatus": {
            "type": "string",
            "enum": [
                "created",
                "confirmed",
                "canceled",
                "completed"
            ],
            "x-enum-varnames": [
                "BookingStatusCreated",
                "BookingStatusConfirmed",
                "BookingStatusCanceled",
                "BookingStatusCompleted"
            ]
        },
        "sqlc.PaymentMethod": {
            "type": "string",
            "enum": [
                "cash",
                "card",
                "online"
            ],
            "x-enum-varnames": [
                "PaymentMethodCash",
                "PaymentMethodCard",
                "PaymentMethodOnline"
            ]
        },
        "sqlc.PaymentStatus": {
            "type": "string",
            "enum": [
                "pending",
                "paid",
                "failed",
                "refunded"
            ],
            "x-enum-varnames": [
                "PaymentStatusPending",
                "PaymentStatusPaid",
                "PaymentStatusFailed",
                "PaymentStatusRefunded"
            ]
        },
        "sqlc.PositionType": {
            "type": "string",
            "enum": [
                "admin",
                "seller",
                "operator",
                "tech"
            ],
            "x-enum-varnames": [
                "PositionTypeAdmin",
                "PositionTypeSeller",
                "PositionTypeOperator",
                "PositionTypeTech"
            ]
        },
        "sqlc.ZoneType": {
            "type": "string",
            "enum": [
                "game",
                "event",
                "vip",
                "lounge",
                "sys"
            ],
            "x-enum-varnames": [
                "ZoneTypeGame",
                "ZoneTypeEvent",
                "ZoneTypeVip",
                "ZoneTypeLounge",
                "ZoneTypeSys"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PlayGround API",
	Description:      "Backend API for PlayGround",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
